name: Automatisation Python

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configurer le cache de pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Installer les dépendances
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "⚠️ Erreur dans requirements.txt"
      - name: Exécuter le script Python avec les identifiants
        env:
          PROJECT_URL: ${{ secrets.PROJECT_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          DBNAME: ${{ secrets.DBNAME }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}        
        run: python data/automatisation_data.py || echo "⚠️ Erreur dans automation_data.py"