name: Automatisation Python

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
    
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter le script Python avec les identifiants
        env:
          PROJECT_URL: ${{ secrets.PROJECT_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          DBNAME: ${{ secrets.DBNAME }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}        
        run: python data/automatisation_data.py
